version: 2.0

py35default: &py35default
  docker:
    - image: circleci/python:3.5
  steps:
   - checkout
   - restore_cache:
      key: py35-{{ .Environment.CIRCLE_SHA1 }}
   - run:
      command: |
        sudo pip install tox
        tox -e $CIRCLE_STAGE
   - save_cache:
      key: py35-{{ .Environment.CIRCLE_SHA1 }}
      paths:
         - ".tox"

py37default: &py37default
  docker:
    - image: circleci/python:3.7
  steps:
   - checkout
   - restore_cache:
      key: py37-{{ .Environment.CIRCLE_SHA1 }}
   - run:
      command: |
        sudo pip install tox
        tox -e $CIRCLE_STAGE
   - save_cache:
      key: py37-{{ .Environment.CIRCLE_SHA1 }}
      paths:
         - ".tox"

jobs:

  flake8:
    <<: *py35default

  py35-dj22-cms37:
    <<: *py35default

  py37-dj22-cms37:
    <<: *py37default

#######################

workflows:
  version: 2
  build:
    jobs:
      - flake8
      - py35-dj22-cms37
      - py37-dj22-cms37
