# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2020-03-31 07:56
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import parler.fields


class Migration(migrations.Migration):

    dependencies = [
        ('aldryn_events', '0026_auto_20180112_1738'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eventsconfigtranslation',
            name='master',
            field=parler.fields.TranslationsForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='translations', to='aldryn_events.EventsConfig'),
        ),
        migrations.AlterField(
            model_name='eventtranslation',
            name='master',
            field=parler.fields.TranslationsForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='translations', to='aldryn_events.Event'),
        ),
        migrations.AlterField(
            model_name='registration',
            name='language_code',
            field=models.CharField(choices=[('de', 'German'), ('en', 'English'), ('zh', 'Chinese')], default='de', max_length=32),
        ),
    ]
